<?php

const LANGUAGES = [
    'medical_file' => 'Medical file',
    'total_mess' => 'You have total',
    'add_medical_file' => 'Add medical file',
    'full_name' => 'Full name',
    'gender' => 'Gender',
    'phone' => 'Phone',
    'birthday' => 'Birthday',
    'status' => 'Status',
    'action' => 'Action',
    'identity_card' => 'Identity card',
    'id' => 'Id',
    'age' => 'Age',
    'view_detail' => 'View detail',

    // Medical file detail
    'personal' => 'Personal',
    'health' => 'Health',
    'main_information' => 'Main information',
    'first_name' => 'First name',
    'last_name' => 'Last name',
    'email_address' => 'Email address',
    'way' => 'Way',
    'district' => 'District',
    'wards' => 'Wards',
    'province' => 'Province',
    'date_of_birth' => 'Date of birth',
    'other_information' => 'Other information',
    'have_health_insurance' => 'Have health insurance',
    'health_insurance_number' => 'Health insurance number',
    'expiration_date' => 'Expiration date',
    'qr_code' => 'Qr code',
    'not_health_insurance' => 'Not Health Insurance',
    'health_insurance' => 'Health Insurance',
    'edit_information' => 'Edit information',
    're_generate_qr_image' => 'Re-generate QR image',
    'covid_vaccination' => 'Covid vaccine information',
    'injection' => 'Injection',
    'name_vaccine' => 'Name vaccine',
    'vaccination_date' => 'Date',
    'edit' => 'Edit',
    'title_generate_qr' => 'Are you sure re-generate QR image?',
    'generate' => 'Generate',
    'medical_examination_history' => 'Medical Examination History',
    'add_health' => 'Add medical examination',
    'summary' => 'Summary',
    'description' => 'Description',
    'doctor_advice' => 'Doctor\'s advice',
    'views_prescription' => 'Views prescription',
    'prescription_information' => 'Prescription Information',
    'address' => 'Address',
    'name' => 'Name',
    'quantity' => 'Quantity',
    'dosage' => 'Dosage',
    'add_prescription' => 'Add prescription',
    'date_of_the_examination' => 'Date of the examination',
    'delete_health' => 'Delete medical examination history',
    'alert_delete_health' => 'Are you sure delete health?',
    'prefix_content_delete' => 'The medical examination history have id',
    'suffix_content_delete' => 'after being deleted will not be able to recover.',
    'edit_prescription' => 'Edit prescription',

    //Medical file add
    'add' => 'Add',
    'male' => 'Male',
    'female' => 'Female',

    'identity_card_exist' => 'The identity card existed',
    'require_birthday' => 'Please enter birthday',
    'add_medical_file_fail' => 'Add medical file fail',
    'add_health_insurance' => 'Add health insurance fail',
    'update_medical_file_fail' => 'Add medical file fail',
    'update_health_insurance' => 'Add health insurance fail',
    'delete_medical_file_fail' => 'Delete medical file fail',
    'delete_medical_file_success' => 'Delete medical file success',
    'require_user' => 'Please choose user',

    'add_health_fail' => 'Add medical examination fail',
    'add_health_success' => 'Add medical examination success',
    'edit_health_fail' => 'Edit medical examination fail',
    'edit_health_success' => 'Edit medical examination success',

    'prescription' => 'Prescription',

    'edit_prescription_fail' => 'Edit prescription fail',
    'edit_prescription_success' => 'Edit prescription success',
    'add_prescription_fail' => 'Add prescription fail',
    'add_prescription_success' => 'Add prescription success',
    'delete_health_success' => 'Delete medical examination fail',
    'delete_health_fail' => 'Delete medical examination success',
];
