<?php

const LANGUAGES = [
    'medical_file' => 'Hồ sơ bệnh nhân',
    'total_mess' => 'Bạn có tổng cộng',
    'add_medical_file' => 'Thêm hồ sơ',
    'full_name' => 'Họ và tên',
    'gender' => 'Giới tính',
    'phone' => 'Điện thoại',
    'birthday' => 'Ngày sinh',
    'action' => 'Hành động',
    'identity_card' => 'CMND/CCCD',
    'id' => 'Mã hồ sơ',
    'age' => 'Tuổi',
    'view_detail' => 'Xem chi tiết',

    // Medical file detail
    'personal' => 'Cá nhân',
    'health' => 'Sức khỏe',
    'main_information' => 'Thông tin chính',
    'first_name' => 'Họ đệm',
    'last_name' => 'Tên',
    'email_address' => 'Địa chỉ email',
    'way' => 'Đường',
    'district' => 'Phường/xã',
    'wards' => 'Quận/huyện',
    'province' => 'Tỉnh/thành phố',
    'date_of_birth' => 'Ngày sinh',
    'other_information' => 'Thông tin khác',
    'have_health_insurance' => 'Có bảo hiểm y tế',
    'health_insurance_number' => 'Mã số bảo hiểm',
    'expiration_date' => 'Ngày hết hạn',
    'qr_code' => 'Mã Qr',
    'not_health_insurance' => 'Không có bảo hiểm',
    'health_insurance' => 'Có bảo hiểm',
    'edit_information' => 'Chỉnh sửa thông tin',
    're_generate_qr_image' => 'Tạo lại Qr',
    'covid_vaccination' => 'Thông tin tiêm chủng',
    'injection' => 'Mũi',
    'name_vaccine' => 'Tên vaccine',
    'vaccination_date' => 'Ngày tiêm',
    'edit' => 'Sửa',
    'title_generate_qr' => 'Bạn có chắc muốn tạo lại QR',
    'generate' => 'Tạo',
    'medical_examination_history' => 'Lịch sử khám bệnh',
    'add_health' => 'Thêm phiếu khám',
    'summary' => 'Tóm tắt',
    'description' => 'Mô tả',
    'doctor_advice' => 'Lời khuyên của bác sĩ',
    'views_prescription' => 'Xem đơn thuốc',
    'prescription_information' => 'Thông tin đơn thuốc',
    'address' => 'Địa chỉ',
    'name' => 'Tên thuốc',
    'quantity' => 'Số lượng',
    'dosage' => 'Liều dùng',
    'add_prescription' => 'Thêm đơn thuốc',
    'date_of_the_examination' => 'Ngày khám',
    'delete_health' => 'Xóa lịch sử khám bệnh',
    'alert_delete_health' => 'Bạn có chắc là muốn xóa lịch sử khám bệnh?',
    'prefix_content_delete' => 'Lịch sử khám bệnh có mã là ',
    'suffix_content_delete' => 'Sau khi xóa sẽ không thể phục hồi.',
    'edit_prescription' => 'Sửa đơn thuốc',

    //Medical file add
    'add' => 'Thêm',
    'male' => 'Nam',
    'female' => 'Nữ',

    'identity_card_exist' => 'CMND/CCCD đã tồn tại',
    'require_birthday' => 'Vui lòng chọn ngày sinh',
    'add_medical_file_fail' => 'Thêm hồ sơ bệnh nhân không thành công',
    'add_health_insurance' => 'Thêm BHYT không thành công',
    'update_medical_file_fail' => 'Chỉnh sửa hồ sơ bệnh nhân không thành công',
    'update_health_insurance' => 'Chỉnh sửa BHYT không thành công',
    'delete_medical_file_fail' => 'Xóa hồ sơ bệnh nhân không thành công',
    'delete_medical_file_success' => 'Xóa hồ sơ bệnh nhân thành công',
    'require_user' => 'Vui lòng chọn bệnh nhân',

    'add_health_fail' => 'Thêm phiếu khám không thành công',
    'add_health_success' => 'Thêm phiếu khám thành công',
    'edit_health_fail' => 'Sửa phiếu khám không thành công',
    'edit_health_success' => 'Sửa phiếu khám thành công',

    'prescription' => 'Đơn thuốc',

    'edit_prescription_fail' => 'Sửa đơn thuốc không thành công',
    'edit_prescription_success' => 'Sửa đơn thuốc thành công',
    'add_prescription_fail' => 'Thêm đơn thuốc không thành công',
    'add_prescription_success' => 'Thêm đơn thuốc thành công',
    'delete_health_success' => 'Xóa lịch sử khám bệnh thành công',
    'delete_health_fail' => 'Xóa lịch sử khám bệnh không thành công',
];
