<?php

const LANGUAGES = [
    // User List
    'full_name' => 'Full name',
    'role' => 'Role',
    'email' => 'Email',
    'phone' => 'Phone',
    'birthday' => 'Birthday',
    'status' => 'Status',
    'action' => 'Action',
    'user_list' => 'User list',
    'total_mess' => 'You have total',
    'user' => 'user(s)',
    'add_user' => 'Add user',
    'view_detail' => 'View detail',
    'reset_password' => 'Reset password',
    'delete_user' => 'Delete user',
    'title_delete' => 'Are you sure delete user?',
    'title_delete_after' => 'after being deleted will not be able to recover',
        // User detail
    'login_information' => 'Login Information',
    'personal' => 'Personal',
    'first_name' => 'First name',
    'last_name' => 'Last name',
    'email_address' => 'Email address',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'administrator_permission' => 'Administrator',
    'doctor_permission' => 'Doctor',
    'user_permission' => 'User',
    'personal_information' => 'Personal Information',
    'way' => 'Way',
    'district' => 'District',
    'wards' => 'Wards',
    'province' => 'Province',
    'identity_card' => 'Identity card',
    'date_of_birth' => 'Date of birth',
    'gender' => 'Gender',
    'edit_user' => 'Edit user',
    'change_avatar' => 'Change avatar',
    'choose_file' => 'Choose file',
    'users' => 'User(s)',
    'user_id' => 'User ID',
    'password' => 'Password',
    'confirm_password' => 'Confirm password',
    'language' => 'Language',
    'english' => 'English',
    'vietnamese' => 'Vietnamese',
    'male' => 'Male',
    'female' => 'Female',


    'update_avatar_success' => 'Update avatar success',
    'update_avatar_fail' => 'Update avatar fail',
    'update_user_success' => 'Update user success',
    'update_user_fail' => 'Update user fail',
    'please_enter_password' => 'Please enter password',
    'password_not_match' => 'Password not match',
    'email_already_exist' => 'Email already exists',
    'add_user_fail' => 'Add user fail',
    'add_user_profile_fail' => 'Add user profile fail',
    'delete_user_fail' => 'Delete user fail',
    'delete_user_success' => 'Delete user success',
    'reset_password_fail' => 'Reset password fail',
    'reset_password_success' => 'Reset password success',
];
